#!/bin/bash

# dependencies /////////////////////////////////////////////////////////////////

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^update=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^update=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	# script arguments for escalation

	self_arguments=("${@}")
fi

# superuser ////////////////////////////////////////////////////////////////////

frobulator.escalate

# script ///////////////////////////////////////////////////////////////////////

frobulator.script

# version //////////////////////////////////////////////////////////////////////

version="2026-09-29"

# usage ////////////////////////////////////////////////////////////////////////

while (($#))
do
	case "${1}"
	in
		-f|--file)
			image="${2}"

			shift
		;;

		-d|--download)
			inline="0"
		;;

		-n|--name)
			name="1"
		;;

		-x|--width)
			width="${2}"

			shift
		;;

		-y|--height)
			height="${2}"

			shift
		;;

		-s|--stretch)
			ratio="0"
		;;

		-t|--type)
			type="${2}"

			shift
		;;

		-b|--block)
			block="1"
		;;

		-h|--help)
			echo
			echo -e "Usage: ./${script} -f [File] -d | -n | -x [Width] -y [Height] | -s | -t [Type] | -b | -h"
			echo
			echo -e "Options:"
			echo
			echo -e "-f, --file        Specify image [f]ile to display."
			echo
			echo -e "-d, --download    Send image as a file [d]ownload instead."
			echo
			echo -e "-n, --name        Display file [n]ame after the image."
			echo
			echo -e "-x, --width       Specify image width in cells or pi[x]els."
			echo
			echo -e "                  [ n ]    [ character cells           ]"
			echo -e "                  [ npx ]  [ pixels                    ]"
			echo -e "                  [ n% ]   [ percent of session width  ]"
			echo -e "                  [ auto ] [ Default - from image size ]"
			echo
			echo -e "-y, --height      Specify displa[y] height of the image."
			echo
			echo -e "                  [ n ]    [ character cells           ]"
			echo -e "                  [ npx ]  [ pixels                    ]"
			echo -e "                  [ n% ]   [ percent of session height ]"
			echo -e "                  [ auto ] [ Default - from image size ]"
			echo
			echo -e "-s, --stretch     Set image [s]tretch to the given width and height."
			echo
			echo -e "-t, --type        Specify file [t]ype hint for parsing."
			echo
			echo -e "                  [ mime type ]      [ text/markdown ]"
			echo -e "                  [ language name ]  [ java          ]"
			echo -e "                  [ file extension ] [ .sh           ]"
			echo
			echo -e "-b, --block       Send image as a single [b]lock sequence."
			echo
			echo -e "                  [ multipart ] [ Default - inside tmux or screen ]"
			echo
			echo -e "-h, --help        Show [h]elp and usage information."
			echo
			echo -e "Examples:"
			echo
			echo -e "./${script} -f image.png -x 250px -y 250px -s"
			echo
			echo -e "cat image.png | ./${script} -x 75%"
			echo
			echo -e "'${script}'       [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} -f [File] -d | -n | -x [Width] -y [Height] | -s | -t [Type] | -b | -h"
			echo
			echo -e "Unknown option: '${script} ${1}':"
			echo -e "Type './${script} -h' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# functions ////////////////////////////////////////////////////////////////////

image_osc () {

	# osc - opening sequence characters
	# verify terminal multiplexer instance and type

	if [[ "${TERM}" == screen* ]] ||
		[[ "${TERM}" == tmux* ]]
	then
		printf "\033Ptmux;\033\033]"
	else
		printf "\033]"
	fi
}

image_tsc () {

	# tsc - termination secquence characters
	# verify terminal multiplexer instance and type

	if [[ "${TERM}" == screen* || "${TERM}" == tmux* ]]
	then
		printf "\a\033\\"
	else
		printf "\a"
	fi
}

image_unit () {

	unit="${1}"

	# verify image sizing unit format:
	# [n] / [n]px / [n]% / auto

	if [[ ! "$1" =~ ^(:?[0-9]+(:?px|%)?|auto)$ ]]
	then
		frobulator.err "Invalid image size unit" "[ '${unit}' ]"

		exit 1
	fi
}

image_parse () {

	# image_parse image inline encoding name width height ratio type block

	# ${1} image:       image filename

	# ${2} inline:      0 - download image
	#                   1 - display inline

	# ${3} encoding:    base64-encoded image contents

	# ${4} name:        0 - no filename display after image processing
	#                   1 - display filename after image processing

	# ${5} width:       set image output width - numeric digits only
	#                   n    - character cells
	#                   npx  - pixels
	#                   n%   - percentage (width only or height only)
	#                   auto - automatic calculation to terminal output

	# ${6} height:      set image output height - numeric digits only
	#                   n    - character cells
	#                   npx  - pixels
	#                   n%   - percentage (width only or height only)
	#                   auto - automatic calculation to terminal output

	# ${7} ratio:       0 - fill specified height or width value to maximum terminal output
	#                   1 - fill specified height or width value to maximum terminal output without deformation

	# ${8} type:        file type hint
	#                   "" - empty value [Default]
	#                   mimetype  - ex.: application/json
	#					name      - ex.: Python
	#					extension - ex.: .sh

	# ${9} block:       1 - parse and send as one monolithic block/control sequence
	#                   0 - parse and send as multiple 512-byte block/control sequences

	image="${1}"
	inline="${2}"
	encoding="${3}"
	name="${4}"
	width="${5}"
	height="${6}"
	ratio="${7}"
	type="${8}"
	block="${9}"

	echo

	# open sequence - begin transfer

	image_osc

	printf "1337;"

	if [[ "${block}" -eq 1 ]]
	then
		printf "File"
	else
		printf "MultipartFile"
	fi

	printf "=inline=%s" "${inline}"

	printf ";size=%d" $(printf "%s" "${encoding}" | base64 -d -i | wc -c)

	if [ -n "${image}" ]
	then
		printf ";name=%s" "$(printf "%s" "${image}" | base64 -w 0)"
	fi

	if [ -n "${width}" ]
	then
		printf ";width=%s" "${width}"
	fi

	if [ -n "${height}" ]
	then
		printf ";height=%s" "${height}"
	fi

	if [ -n "${ratio}" ]
	then
		printf ";preserveAspectRatio=%s" "${ratio}"
	fi

	[ -n "${type}" ] && printf ";type=%s" "${type}"

	if [[ "${block}" -eq 1 ]]
	then
		printf ":%s" "${encoding}"

		image_tsc
	else
		image_tsc

		# split into 512-byte parts:
		# optimizes parsing through terminal multiplexer

		bytes=512

		mapfile -t parts < <(printf "%s" "${encoding}" | fold -w "${bytes}")

		# load byte stream

		for part in "${parts[@]}"
		do
			image_osc

			printf '1337;FilePart=%s' "${part}"

			image_tsc
		done

		# terminate sequence

		image_osc

		printf '1337;FileEnd'

		image_tsc
	fi

	echo

	if [ "${name}" = "1" ]
	then
		echo "Image: ${image}"
		echo
	fi
}

image_print () {

	# stdin only without a file

	if [ "${input}" = "stdin" ] && [ -z "${image}" ]
	then
		encoding=$(cat | base64 -w 0)
	fi

	image_parse "${image}" "${inline}" "${encoding}" "${name}" "${width}" "${height}" "${ratio}" "${type}" "${block}"

}

# defaults /////////////////////////////////////////////////////////////////////

inline="${inline:-1}"

name="${name:-0}"

ratio="${ratio:-1}"

# multipart inside tmux or screen, single block otherwise

if [ -z "${block}" ]
then
	if [[ "${TERM}" == screen* ]] || [[ "${TERM}" == tmux* ]]
	then
		block="0"
	else
		block="1"
	fi
fi

type="${type:-}"

# validate arguments

for value in "${image}" "${width}" "${height}" "${type}"
do
	if [[ "${value}" = -* ]]
	then
		frobulator.err "Missing option argument" "[ ${value} ]"

		exit 1
	fi
done

# options //////////////////////////////////////////////////////////////////////

if [ -t 0 ]
then
	# 'stdin' is a tty

	input="tty"
else
	input="stdin"
fi

# variables ////////////////////////////////////////////////////////////////////

if [ -z "${image}" ] && [ "${input}" = "tty" ]
then
	frobulator.err "Missing image file."

	exit 1
fi

if [ -z "${image}" ]
then
	:

elif [ -r "${image}" ]
then
	encoding=$(cat "${image}" | base64 -w 0)

elif [[ "${image}" =~ ^https?://[a-zA-Z0-9.-]+(\.[a-zA-Z]{2,})?(:[0-9]{1,5})?(/.*)?$ ]]
then
	# curl status, not base64

	encoding=$(curl -f -s -L "${image}" | base64 -w 0; exit "${PIPESTATUS[0]}")

	frobulator.complete halt "Could not retrieve image" "[ ${image} ]"

else
	frobulator.err "File not found" "[ ${image} ]"

	exit 2
fi

if [ -n "${height}" ]
then
	image_unit "${height}"
fi

if [ -n "${width}" ]
then
	image_unit "${width}"
fi

image_print
